version: '3.9'

services:
  backend:
    image: 'kupipodariday-backend'
    container_name: 'wishes-backend'
    restart: on-failure
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    depends_on:
      - postgres
    env_file:
      - /backend/.env
    networks:
      - backend_network

  frontend:
    image: 'kupipodariday-frontend'
    container_name: 'wishes-frontend'
    restart: on-failure
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3010:80'
    networks:
      - frontend_network

  postgres:
    image: 'postgres'
    container_name: 'wishes-postgres'
    restart: always
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - ./backend/.env
    networks:
      - backend_network
      - frontend_network

  adminer:
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - backend_network

networks:
  backend_network:
  frontend_network:

volumes:
  postgres_data: